### ISSUE TITLE
Temporary branches not removed

### ISSUE THREAD

**Issue by eelco** [tibdex/github-rebase#6] opened 2018-08-29 14:01 UTC
Using (a fork of) Autorebase, I now see this in our repo:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/12829/44792631-9eae2800-aba4-11e8-8276-3802ab684034.png">

**Comment by eelco** [comment] 2018-08-29 14:30
I think this happens when there is a merge conflict, btw.

**Comment by tibdex** [comment] 2018-09-06 00:54
The project has [a test covering merge conflicts](https://github.com/tibdex/github-rebase/blob/00dc4958abdb3d70b61d5226eb394986d9739d72/tests/index.test.js#L132-L212).

This test successfully executes on CircleCI targeting https://github.com/tibdex/github-apps-test. You can see in this repo that even when there is a merge conflict, `github-rebase` and its dependency `github-cherry-pick` clean up after themselves. Indeed, they both use [this try/finally logic](https://github.com/tibdex/shared-github-internals/blob/e1daf06ce7e32a4db3024e1a85f193ff83dcadb8/src/git.js#L151-L175).

The only reason I can see for the temporary branches not being deleted would be because you're hitting [GitHub REST API's rate limit](https://developer.github.com/v3/rate_limit/).

**Comment by tibdex** [comment] 2018-09-16 16:42
Closing because I can't reproduce and there are already tests covering this.

**Closed** 2018-09-16 16:42 UTC
